insert into public.questions (
  source_ref,
  text,
  image_url,
  option_a,
  option_b,
  option_c,
  option_d,
  option_e,
  correct_answer,
  explanation,
  subject,
  exam_origin,
  difficulty,
  year,
  tags
) values
(
  'enem-2020-geo-001',
  'Em 2019, a taxa de desmatamento na Amazônia voltou ao centro do debate público. Em análises geográficas, esse processo está associado, sobretudo, à expansão de atividades produtivas sobre a fronteira agrícola. Qual consequência territorial decorre desse processo?',
  'https://placehold.co/600x400?text=Mapa+da+Amazônia',
  'Redução da integração logística regional.',
  'Aumento do isolamento das cidades médias.',
  'Ampliação do uso do solo para atividades agropecuárias.',
  'Substituição da vegetação por áreas exclusivamente urbanas.',
  'Diminuição da pressão fundiária em áreas protegidas.',
  'C',
  'A alternativa C está correta porque o avanço da fronteira agrícola converte áreas florestais em usos agropecuários, alterando a organização do território.',
  'Geografia',
  'ENEM',
  'medium',
  2020,
  array['amazônia', 'desmatamento', 'fronteira agrícola']
),
(
  'enem-2019-mat-002',
  'Um estudante precisa escolher entre dois planos de internet. O plano A custa R$ 40,00 por mês e cobra R$ 2,00 por GB excedente. O plano B custa R$ 55,00 por mês e inclui tudo sem taxa extra. A partir de qual consumo o plano B passa a ser mais vantajoso?',
  null,
  'A partir de 6 GB excedentes.',
  'A partir de 7,5 GB excedentes.',
  'A partir de 8 GB excedentes.',
  'A partir de 10 GB excedentes.',
  'A partir de 12 GB excedentes.',
  'B',
  'Igualando os custos: 40 + 2x = 55. Logo, 2x = 15 e x = 7,5. Acima desse valor, o plano B compensa.',
  'Matemática',
  'ENEM',
  'easy',
  2019,
  array['função afim', 'comparação de planos']
),
(
  'enem-2021-ling-003',
  'Em um anúncio publicitário, a repetição intencional de palavras e sons pode ser usada para reforçar uma mensagem e facilitar sua memorização. Esse recurso expressivo está relacionado principalmente à função',
  null,
  'metalinguística, porque explica o próprio código.',
  'apelativa, porque busca influenciar o comportamento do receptor.',
  'referencial, porque apresenta dados objetivos.',
  'fática, porque apenas testa o canal.',
  'emotiva, porque centra a mensagem no emissor.',
  'B',
  null,
  'Linguagens',
  'ENEM',
  'medium',
  2021,
  array['funções da linguagem', 'publicidade']
),
(
  'fuvest-2018-fis-004',
  'Um corpo é lançado verticalmente para cima com velocidade inicial de 20 m/s, desprezando a resistência do ar. Considerando g = 10 m/s², o tempo total de subida e descida até o ponto de lançamento é',
  null,
  '1 s',
  '2 s',
  '3 s',
  '4 s',
  '5 s',
  'D',
  'O tempo de subida é v/g = 20/10 = 2 s. Como o movimento é simétrico, o tempo total é 4 s.',
  'Física',
  'FUVEST',
  'easy',
  2018,
  array['lançamento vertical', 'cinemática']
),
(
  'fuvest-2020-his-005',
  'No contexto da Primeira República brasileira, a chamada política dos governadores pode ser entendida como',
  null,
  'o fortalecimento do federalismo com acordos entre elites estaduais e o poder central.',
  'a ampliação do voto secreto e da participação popular.',
  'a substituição do café por uma economia industrial nacional.',
  'o enfraquecimento dos coronéis no interior.',
  'a centralização militar típica do Estado Novo.',
  'A',
  null,
  'História',
  'FUVEST',
  'medium',
  2020,
  array['primeira república', 'política dos governadores']
),
(
  'fuvest-2022-port-006',
  'Em textos literários, a ambiguidade pode ser um recurso estético importante. Quando um verso admite mais de uma interpretação possível, isso ocorre porque a linguagem literária',
  null,
  'elimina completamente o contexto.',
  'recusa qualquer construção figurada.',
  'permite polissemia e múltiplos sentidos.',
  'deve ser sempre objetiva e técnica.',
  'reduz o papel do leitor na construção do significado.',
  'C',
  null,
  'Português',
  'FUVEST',
  'medium',
  2022,
  array['literatura', 'interpretação']
),
(
  'unicamp-2019-bio-007',
  'Em um ecossistema aquático, o aumento excessivo de nutrientes pode favorecer florações de algas e comprometer a disponibilidade de oxigênio dissolvido. Esse fenômeno é conhecido como',
  'https://placehold.co/600x400?text=Gráfico+de+Oxigênio',
  'biomagnificação.',
  'eutrofização.',
  'sucessão ecológica.',
  'mutualismo.',
  'nicho ecológico.',
  'B',
  'A eutrofização ocorre quando o excesso de nutrientes aumenta a produção de algas e reduz o oxigênio disponível após sua decomposição.',
  'Biologia',
  'UNICAMP',
  'medium',
  2019,
  array['ecologia', 'eutrofização']
),
(
  'unicamp-2021-qui-008',
  'Uma solução aquosa apresentou pH igual a 3. Isso significa que a concentração de íons H+ nessa solução é igual a',
  null,
  '10^-1 mol/L',
  '10^-2 mol/L',
  '10^-3 mol/L',
  '10^-4 mol/L',
  '3 mol/L',
  'C',
  null,
  'Química',
  'UNICAMP',
  'easy',
  2021,
  array['pH', 'química geral']
),
(
  'unicamp-2022-mat-009',
  'Uma progressão aritmética tem primeiro termo igual a 5 e razão 3. O quinto termo dessa sequência é',
  null,
  '14',
  '15',
  '16',
  '17',
  '18',
  'D',
  null,
  'Matemática',
  'UNICAMP',
  'easy',
  2022,
  array['progressão aritmética']
),
(
  'vunesp-2020-atual-010',
  'A discussão sobre transição energética ganhou força nos últimos anos. Entre as medidas abaixo, aquela mais diretamente associada à redução da dependência de combustíveis fósseis é',
  null,
  'ampliar o uso de termelétricas a carvão.',
  'incentivar fontes renováveis como solar e eólica.',
  'subsidiar exclusivamente o diesel.',
  'expandir a queima de óleo combustível em áreas urbanas.',
  'reduzir investimentos em eficiência energética.',
  'B',
  null,
  'Atualidades',
  'VUNESP',
  'medium',
  2020,
  array['energia', 'sustentabilidade']
),
(
  'vunesp-2021-log-011',
  'Considere a sequência lógica 2, 6, 12, 20, 30, ... O próximo termo é',
  null,
  '36',
  '40',
  '42',
  '44',
  '48',
  'C',
  'As diferenças são 4, 6, 8, 10. A próxima diferença é 12, então 30 + 12 = 42.',
  'Raciocínio Lógico',
  'VUNESP',
  'medium',
  2021,
  array['sequências', 'lógica']
),
(
  'vunesp-2023-port-012',
  'Na norma-padrão, o emprego da crase ocorre corretamente em:',
  null,
  'Vou a escola todos os dias.',
  'Entreguei o relatório a diretora.',
  'Cheguei à universidade antes do horário.',
  'O evento começará as oito horas.',
  'Refiro-me a uma decisão importante.',
  'C',
  null,
  'Língua Portuguesa',
  'VUNESP',
  'medium',
  2023,
  array['crase', 'gramática']
)
on conflict (source_ref) do update
set
  text = excluded.text,
  image_url = excluded.image_url,
  option_a = excluded.option_a,
  option_b = excluded.option_b,
  option_c = excluded.option_c,
  option_d = excluded.option_d,
  option_e = excluded.option_e,
  correct_answer = excluded.correct_answer,
  explanation = excluded.explanation,
  subject = excluded.subject,
  exam_origin = excluded.exam_origin,
  difficulty = excluded.difficulty,
  year = excluded.year,
  tags = excluded.tags;
